### ISSUE TITLE
error in running the controller 

### ISSUE THREAD

**Issue by BasmaHegab** [sdnwiselab/sdn-wise-java#20]
hi 
I want to run the controller but there is something wrong. I followed the instructions, but when I reach "java -jar target/01-GetStarted.jar"
It gives me
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/sdnwiselab/sdnwise/loader/SdnWise : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482

Can you help me to solve the problem, please.

**Comment by SebMilardo** [comment]
Hi, 

sdn-wise-java was compiled using java 1.8. If you have a lower version please upgrade it

You can check you version using `java -version`

In order to have a working controller the output of the previous command should be something like:

`java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)`
